run_client:
	@echo "Running client..."
	@souce venv/bin/activate && python3 client_echo3_udp.py

run_server:
	@echo "Running server..."
	@souce venv/bin/activate && python3 server_echo3_udp.py

run_pirate:
	@echo "Running pirate..."
	@souce venv/bin/activate && python3 pirate_echo3_udp.py